language: node_js
node_js:
- 10.15.3
addons:
  ssh_known_hosts: rnk.party
branches:
  only:
  - master
  - staging
before_install:
- rvm install 2.2.2
- openssl aes-256-cbc -K $encrypted_e5fe645c7fc5_key -iv $encrypted_e5fe645c7fc5_iv
  -in ./.travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
install:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
