language: node_js
node_js:
  - "stable"
addons:
  ssh_known_hosts: rnk.party
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e5fe645c7fc5_key -iv $encrypted_e5fe645c7fc5_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 600 deploy_rsa
- mv deploy_rsa ~/.ssh/id_rsa
install:
- npm install
script:
- npm run build
after_success:
- bash deploy.sh
