language: node_js
node_js:
- 4.3.1
addons:
  ssh_known_hosts: webhost.rnk.party
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_e5fe645c7fc5_key -iv $encrypted_e5fe645c7fc5_iv
  -in travis_rsa.enc -out travis_rsa -d
- rvm install 2.2.2
- chmod 600 ~/.ssh/travis_rsa
install:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
